# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CupNSpoon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CupNSpoon
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod ‘Kingfisher’, ‘~> 3.0’

end
