# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CupNSpoon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CupNSpoon
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod ‘Kingfisher’, ‘~> 3.0’
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

end
